#!/usr/bin/env php
<?php

// require __DIR__ . '/../../autoload.php';
require __DIR__ . '/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Laravel Scaffolder', '0.1');
$app->add(new Alexdover\Scaffolder\Console\UpCommand);

$app->run();